[package]
name = "tonepush-cli"
description = "Edit Line 6 HX and Sonulab StompStation PRO guitar processors from the command line"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "tonepush"
path = "src/main.rs"

[dependencies]
hx-proto.workspace = true
hx-usb.workspace = true
voidx-proto.workspace = true
voidx-client.workspace = true
clap.workspace = true
anyhow.workspace = true
serde_json = "1"
hx-catalog.workspace = true
atomic-write-file = "0.3.1"
